title: bontalor # name of the site
url: https://bonta.lor.moe # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)

permalink: /:categories/:title/

favicon: "assets/imgs/favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

oomf_buttons:
  - url: "https://bonta.lor.moe/"
    img: "/assets/88x31/bontalor.gif"
    alt: "bontalor"
  - url: "https://kwebs.ca/"
    img: "/assets/88x31/kwebs.gif"
    alt: "kwebs"
  - url: "https://mentalstrainrecords.com/"
    img: "/assets/88x31/MSR.gif"
    alt: "mental strain records"

other_buttons:
  - url: "#"
    img: "assets/88x31/no_external_sources.png"
    alt: "no external sources"
    new_tab: false
  - url: "https://archlinux.org/"
    img: "/assets/88x31/archlinux.gif"
    alt: "arch linux"
  - url: "https://eightyeightthirty.one/"
    img: "/assets/88x31/eightyeightthirty.one.png"
    alt: "88x31"
  - url: "https://proxmox.com/"
    img: "/assets/88x31/proxmox.gif"
    alt: "proxmox"
  - url: "https://firefox.com/"
    img: "/assets/88x31/anything_but_chrome.gif"
    alt: "firefox"
  - url: "https://ublockorigin.com/"
    img: "/assets/88x31/ublockorigin.png"
    alt: "ublock"
  - url: "https://hbc.hackmii.com/"
    img: "/assets/88x31/homebrew.png"
    alt: "homebrew"
  - url: "https://seized.fyi/"
    img: "/assets/88x31/seized.gif"
    alt: "seized"
  - url: "https://archive.org/"
    img: "/assets/88x31/archive.org.png"
    alt: "archive"
  - url: "https://steampowered.com/"
    img: "/assets/88x31/steam.gif"
    alt: "steam"
  - url: "https://half-life.com/"
    img: "/assets/88x31/hl.gif"
    alt: "halflife"
  - url: "https://thinkwithportals.com/"
    img: "/assets/88x31/portal.jpg"
    alt: "portal"
  - url: "https://osu.ppy.sh/"
    img: "/assets/88x31/osu.png"
    alt: "osu"
  - url: "https://catbox.moe/"
    img: "/assets/88x31/catbox.png"
    alt: "catbox"
  - url: "https://myanimelist.net/"
    img: "/assets/88x31/mal.png"
    alt: "myanimelist"
    
theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ". . /" # customize text for homepage link in post layout
  date_format: "%m-%d-%Y" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
